// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcsHbwoPA4xYgjoKW_tiZZ5C7J3V75nns',
    appId: '1:709479408697:android:5c4122ae908503b37dd9e8',
    messagingSenderId: '709479408697',
    projectId: 'motocon-v3-iot',
    databaseURL: 'https://motocon-v3-iot-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'motocon-v3-iot.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKJ6eQpZ4egCeRxH_N8MxCEOxWlacB4yM',
    appId: '1:709479408697:ios:6bd1d0d1f77f35057dd9e8',
    messagingSenderId: '709479408697',
    projectId: 'motocon-v3-iot',
    databaseURL: 'https://motocon-v3-iot-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'motocon-v3-iot.firebasestorage.app',
    iosClientId: '709479408697-jk16qpov0a72v1bi9rds1i2i58m7s4fn.apps.googleusercontent.com',
    iosBundleId: 'app.saron.com',
  );

}