// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB445i5gH-UuCt3tEiLtJpm71Xm2YCf_Rk',
    appId: '1:518607947838:android:608212879835a716fe696f',
    messagingSenderId: '518607947838',
    projectId: 'saron-app-1ea19',
    databaseURL: 'https://saron-app-1ea19-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'saron-app-1ea19.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqmAxciZjU8CUjpQgYAIFoxUVE-DpVw_0',
    appId: '1:518607947838:ios:037e88b6445d0e13fe696f',
    messagingSenderId: '518607947838',
    projectId: 'saron-app-1ea19',
    databaseURL: 'https://saron-app-1ea19-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'saron-app-1ea19.appspot.com',
    iosBundleId: 'app.saron.com',
  );
}
