// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBF3pOxLvf4ogM4BOWJdT7pwdsy0N9nnxE',
    appId: '1:709479408697:web:b63c581567353eaf7dd9e8',
    messagingSenderId: '709479408697',
    projectId: 'motocon-v3-iot',
    authDomain: 'motocon-v3-iot.firebaseapp.com',
    databaseURL: 'https://motocon-v3-iot-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'motocon-v3-iot.firebasestorage.app',
    measurementId: 'G-1ZVY9X54PD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcsHbwoPA4xYgjoKW_tiZZ5C7J3V75nns',
    appId: '1:709479408697:android:b49f819c29cfe5187dd9e8',
    messagingSenderId: '709479408697',
    projectId: 'motocon-v3-iot',
    databaseURL: 'https://motocon-v3-iot-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'motocon-v3-iot.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKJ6eQpZ4egCeRxH_N8MxCEOxWlacB4yM',
    appId: '1:709479408697:ios:5e0d1740077658bc7dd9e8',
    messagingSenderId: '709479408697',
    projectId: 'motocon-v3-iot',
    databaseURL: 'https://motocon-v3-iot-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'motocon-v3-iot.firebasestorage.app',
    androidClientId: '709479408697-jpr9ncj4l1jub6d1nloa43llk7hlttkq.apps.googleusercontent.com',
    iosClientId: '709479408697-bok5bual6smju71s7esoai7unu0egg3u.apps.googleusercontent.com',
    iosBundleId: 'app.saronsmart.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKJ6eQpZ4egCeRxH_N8MxCEOxWlacB4yM',
    appId: '1:709479408697:ios:5e0d1740077658bc7dd9e8',
    messagingSenderId: '709479408697',
    projectId: 'motocon-v3-iot',
    databaseURL: 'https://motocon-v3-iot-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'motocon-v3-iot.firebasestorage.app',
    androidClientId: '709479408697-jpr9ncj4l1jub6d1nloa43llk7hlttkq.apps.googleusercontent.com',
    iosClientId: '709479408697-bok5bual6smju71s7esoai7unu0egg3u.apps.googleusercontent.com',
    iosBundleId: 'app.saronsmart.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBF3pOxLvf4ogM4BOWJdT7pwdsy0N9nnxE',
    appId: '1:709479408697:web:42b0052d7dcc4bef7dd9e8',
    messagingSenderId: '709479408697',
    projectId: 'motocon-v3-iot',
    authDomain: 'motocon-v3-iot.firebaseapp.com',
    databaseURL: 'https://motocon-v3-iot-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'motocon-v3-iot.firebasestorage.app',
    measurementId: 'G-8GL7MD105J',
  );

}